# Generated by Django 6.0.4 on 2026-04-19 22:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('fips', models.CharField(blank=True, max_length=5)),
                ('state', models.CharField(default='OH', max_length=2)),
                ('county_seat', models.CharField(blank=True, max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_type', models.CharField(choices=[('tester', 'Radon Tester'), ('mitigator', 'Radon Mitigator'), ('both', 'Tester & Mitigator')], max_length=100)),
                ('license', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('business', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(default='OH', max_length=2)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, max_length=120)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radon.county')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('name_ascii', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(default='OH', max_length=2)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('population', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=120)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='radon.county')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(db_index=True, max_length=5, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(default='OH', max_length=2)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('population', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=120)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('land_area', models.BigIntegerField(blank=True, null=True)),
                ('water_area', models.BigIntegerField(blank=True, null=True)),
                ('usepa_radon_zone', models.IntegerField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_codes', to='radon.county')),
            ],
            options={
                'ordering': ['zip'],
            },
        ),
        migrations.CreateModel(
            name='SponsoredListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, max_length=10)),
                ('contractor_type', models.CharField(choices=[('mitigator', 'Radon Mitigator'), ('tester', 'Radon Tester'), ('both', 'Tester & Mitigator')], max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('vanity_url_name', models.SlugField(max_length=150, unique=True)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('address1', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(default='OH', max_length=2)),
                ('zip', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsor-logos/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='sponsor-photos/')),
                ('website', models.URLField(blank=True)),
                ('url_yelp', models.URLField(blank=True)),
                ('url_facebook', models.URLField(blank=True)),
                ('url_nextdoor', models.URLField(blank=True)),
                ('url_google', models.URLField(blank=True)),
                ('about', models.TextField(blank=True, max_length=1000)),
                ('call_to_action', models.CharField(blank=True, default='Contact Us', max_length=100)),
                ('hours', models.CharField(blank=True, max_length=150)),
                ('ratings', models.CharField(blank=True, max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('eff_date_start', models.DateField(blank=True, null=True)),
                ('eff_date_end', models.DateField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contractor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_listing', to='radon.contractor')),
                ('service_cities', models.ManyToManyField(blank=True, related_name='sponsored_listings', to='radon.city')),
                ('service_counties', models.ManyToManyField(blank=True, related_name='sponsored_listings', to='radon.county')),
                ('service_zip_codes', models.ManyToManyField(blank=True, related_name='sponsored_listings', to='radon.zipcode')),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='RadonLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='OH', max_length=2)),
                ('testcount', models.IntegerField()),
                ('testmin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('testmax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('testmean', models.DecimalField(decimal_places=2, max_digits=8)),
                ('teststdev', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('testgeomean', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('usepa_radon_zone', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('pubdate', models.DateField(blank=True, null=True)),
                ('pubsource', models.URLField(blank=True, max_length=500)),
                ('pub_represents_period', models.CharField(blank=True, max_length=500)),
                ('county', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radon_level', to='radon.county')),
                ('zip_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radon_level', to='radon.zipcode')),
            ],
            options={
                'ordering': ['-testmean'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='zip_codes',
            field=models.ManyToManyField(blank=True, related_name='cities', to='radon.zipcode'),
        ),
    ]
